

database:
  driverClass: org.h2.Driver
  user: sa
  url: jdbc:h2:./tictactoe

server:
  applicationConnectors:
    - type: http
      port: 3000

  adminConnectors:
    - type: http
      port: 3001

