

database:
  driverClass: org.h2.Driver
  user: sa
  url: jdbc:h2:./tictactoe

server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 3000
  #applicationConnectors:
  #  - type: http
  #    port: 3000

  #adminConnectors:
  #  - type: http
  #    port: 3001


